import { ItemType } from "./types";

/** Display names shown in the Inventory screen. Mirrors server/src/items/itemNames.ts. */
export const ITEM_DISPLAY_NAMES: Record<ItemType, string> = {
  common_chest: "Common Chest",
  rare_chest: "Rare Chest",
  exotic_chest: "Exotic Chest",
  dagger: "The Poisoned Dagger",
  sigil: "The Sigil of the Iron Vault",
  painting: "The Masterpiece Painting",
  bleeding_coin: "The Bleeding Coin",
  forged_seal: "The Forged Seal",
  vault_ledger_lock: "The Vault Ledger Lock",
  auction_insurance_token: "Auction Insurance Token",
  whispering_coin: "The Whispering Coin",
  tarnished_locket: "The Tarnished Locket",
  chalk_marker: "Chalk Marker",
  twin_faced_coin: "The Twin-Faced Coin",
  wardens_whistle: "The Warden's Whistle",
  phantom_bidder: "Phantom Bidder",
  street_rumor: "Street Rumor",
  dull_blade: "The Dull Blade",
  empty_frame: "The Empty Frame",
  bent_sigil: "The Bent Sigil",
  weighted_dice: "The Weighted Dice",
  gallery_deed: "The Gallery Deed",
  watchers_token: "The Watcher's Token",
  brokers_monopoly: "Broker's Monopoly",
  pickpockets_glove: "The Pickpocket's Glove",
  grudge_ledger: "The Grudge Ledger",
  oathbreakers_dagger: "The Oathbreaker's Dagger",
};

/** Background/text classes for each item's block tile in the Inventory grid. */
export const ITEM_BLOCK_COLORS: Record<ItemType, string> = {
  common_chest: "bg-green-600 text-white",
  rare_chest: "bg-blue-600 text-white",
  exotic_chest: "bg-purple-600 text-white",
  painting: "bg-amber-500 text-white",
  sigil: "bg-indigo-600 text-white",
  dagger: "bg-red-700 text-white",
  bleeding_coin: "bg-gray-900 text-red-400",
  forged_seal: "bg-indigo-400 text-white",
  vault_ledger_lock: "bg-indigo-800 text-white",
  auction_insurance_token: "bg-sky-600 text-white",
  whispering_coin: "bg-sky-800 text-white",
  tarnished_locket: "bg-amber-700 text-white",
  chalk_marker: "bg-stone-500 text-white",
  twin_faced_coin: "bg-yellow-500 text-black",
  wardens_whistle: "bg-indigo-500 text-white",
  phantom_bidder: "bg-sky-900 text-white",
  street_rumor: "bg-stone-600 text-white",
  dull_blade: "bg-red-400 text-white",
  empty_frame: "bg-amber-200 text-amber-900",
  bent_sigil: "bg-indigo-300 text-indigo-900",
  weighted_dice: "bg-yellow-600 text-white",
  gallery_deed: "bg-fuchsia-700 text-white",
  watchers_token: "bg-teal-600 text-white",
  brokers_monopoly: "bg-fuchsia-900 text-white",
  pickpockets_glove: "bg-red-500 text-white",
  grudge_ledger: "bg-red-900 text-white",
  oathbreakers_dagger: "bg-red-800 text-white",
};
